## Python Numpy

In [1]:
## First let us import Numpy LIbrary
import numpy as np

In [12]:
# Declaring a list
agelist = np.random.randint(18, 45, 10)

print(agelist)
## Creating array
agearray = np.array(agelist)

print(agearray)  # Printing the array
print(type(agearray))  # Printing the type

[30 30 25 36 38 38 41 38 36 30]
[30 30 25 36 38 38 41 38 36 30]
<class 'numpy.ndarray'>


In [3]:
## String Array
books = np.array(['Python for Data Science','Intro to Machine Learning','Intro to Deep Learning'])

print(books)  ## Printing the array
type(books)   ## Printing the Type 

['Python for Data Science' 'Intro to Machine Learning'
 'Intro to Deep Learning']


numpy.ndarray

**random()** is used to create random numbers.  It will create the random numbers from [0.0, 1.0].

In [4]:
## Creating 20 random numbers.  It will create 1-d array.
np.random.random(size=10)

array([0.85177615, 0.75433646, 0.02308035, 0.0963214 , 0.21433043,
       0.93994086, 0.75343687, 0.80829292, 0.52594991, 0.71700783])

**rand()** is used to create random numbers between 0 and 1 in a given shape.

In [6]:
## Creating array using rand()
print(np.random.rand(3,3))

## To generate a single random number
np.random.rand()

[[0.77850307 0.76480494 0.54416206]
 [0.29286049 0.69049545 0.04370611]
 [0.06614182 0.20875652 0.77488169]]


0.23260120145969643

**randint()** is used to create random integer numbers from the given range.

In [8]:
## Generating single random number
print(np.random.randint(10,100))

## Creating ramdom integers of size 25
np.random.randint(1,100,25)

34


array([52,  8, 63, 99, 64, 18, 44, 95, 50, 79,  6, 26, 81, 84, 67, 90, 72,
       66, 33, 56, 81, 74, 27, 90, 82])

In [20]:
## Creating Odd numbers
print(np.arange(1,100,2,int))

## Creating even numbers
np.arange(0,100,2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

To create evenly spaced numbers in a given range, we can use linspace function.

In [16]:
## Creating evenly spaced numbers using linspace
print(np.linspace(1, 100, 10))

## Creating zero array
print(np.zeros(10))

## Creating 1 arragy
print(np.ones(10))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
(100-1)/(6-1)

19.8

In [19]:
## Creating arbitrary 3 x 3 array using empty
print(np.empty((3,3), dtype=int))



[[         0          1          0]
 [ 757935405        956          0]
 [       768         12 1701995880]]


In [20]:
## Creating 3 x 3 matrix using fill_value
print(np.full((3,3),fill_value = 11))

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [ ]:
## Creating an identity matrix
print(np.identity(3))

### Array Attributes

In [21]:
## Creating an array with books and its prices
books = np.array([('Python for Data science','Intro to Deep Learning','Python Handbook'),(35,55,20)])

print(books)

## Printing the shape of the array
print("The shape of the array is : ",books.shape)

## Printing the size of the array
print("The number of elements in the array is : ",books.size)

books = np.array([(1.5, 2.5,4.6),(7.9,8,9.0)])

## Printing the data type of the array
print("The data type of the array is : ",books.dtype)

## Printing the dimension of the array
print("The dimension of the array is : ",books.ndim)

[['Python for Data science' 'Intro to Deep Learning' 'Python Handbook']
 ['35' '55' '20']]
The shape of the array is :  (2, 3)
The number of elements in the array is :  6
The data type of the array is :  float64
The dimension of the array is :  2


### Array Operations

In [74]:
## Creating odd and even number arrays
oddnumber = np.array([1, 3, 5, 7])
evennumber = np.array([8,6,2,4])

## Adding two arrays
sum = oddnumber + evennumber
print("Sum of arrays : ", sum)

## Substracting even array from odd array
sub = oddnumber - evennumber
print("Odd array - Even Array : ", sub)

## Multiplying each element of odd array by 5
print("Odd array multiplied by 5 :", oddnumber * 5)

Sum of arrays :  [ 9  9  7 11]
Odd array - Even Array :  [-7 -3  3  3]
Odd array multiplied by 5 : [ 5 15 25 35]


In [81]:
## Matrix Multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1],[7,2],[4,5]])

print(n1)
print(n2)

prod = n1.dot(n2)
print("\n Matrix multiplication : \n\n",prod)

[[1 2 4]
 [3 5 2]]
[[3 1]
 [7 2]
 [4 5]]

 Matrix multiplication : 

 [[33 25]
 [52 23]]


In [82]:
## Element wise multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1, 7],[2,4,5]])

print(n1)
print(n2)

prod = n1 * n2
print("\nElementwise multiplication : \n\n",prod)

[[1 2 4]
 [3 5 2]]
[[3 1 7]
 [2 4 5]]

Elementwise multiplication : 

 [[ 3  2 28]
 [ 6 20 10]]


In [23]:
## Element wise multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1],[2,4]])


print(n1)
print(n2)

print(n1 * n2)

[[1 2 4]
 [3 5 2]]
[[3 1]
 [2 4]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [36]:
## Creating a 1D array
agearray = np.random.randint(18,35,16)
print(agearray)

print(agearray[1::4])

## Convering 1D array to 3x3 array
reshaped_array = agearray.reshape(4,4)
reshaped_array

[26 19 24 27 27 22 19 19 24 22 25 24 30 22 26 31]
[19 22 22 22]


array([[26, 19, 24, 27],
       [27, 22, 19, 19],
       [24, 22, 25, 24],
       [30, 22, 26, 31]])

In [34]:
reshaped_array[1]

array([26, 34, 25, 22])

Simple Statistical analysis

In [88]:
## Creating one dimentinal arrary
salaries = np.array([100000,75000,24000,15000,45000,16000])

## Printing the salaries array
print(salaries)

## Finding the minimum value
print("\nThe minimum Salary is : ", salaries.min())

## Finding the minimum value
print("\nThe maximum Salary is : ", salaries.max())

## The variance in salaries
print("\nThe variance in Salary is : ", salaries.var())

## The variance in salaries
print("\nThe Standard Deviation in Salary is : ", salaries.std())

[100000  75000  24000  15000  45000  16000]

The minimum Salary is :  15000

The maximum Salary is :  100000

The variance in Salary is :  1017138888.8888888

The Standard Deviation in Salary is :  31892.61495846474


In [90]:
## More mathematical functions. np.square()

## Creating an array of sides of square
side_sq = np.array([10,23,15,8,21])

## Printing the area of squares
print("The area of squares are : ", np.square(side_sq))

The area of squares are :  [100 529 225  64 441]


In [92]:
## np.power()

## Finding the volume of cubes
cube_sides = np.array([3,5,7,4,10])

## The volume of cube sides
print("\nThe volume of cube sides are : ", np.power(cube_sides, 3))


The volume of cube sides are :  [  27  125  343   64 1000]


In [93]:
## np.transpose() reverses the order of the matrix.  Suppose if we have M x N, the transpose will change it to N x M

## Creating 2 x 3 matrix
matrix = np.array([(1, 2, 3),(4, 5, 6)])

## Printing the matrix
print("The matrix is : \n",matrix)

## Printing the transpose of the matrix
print("The transposed matrix is : \n", np.transpose(matrix))

The matrix is : 
 [[1 2 3]
 [4 5 6]]
The transposed matrix is : 
 [[1 4]
 [2 5]
 [3 6]]


In [94]:
## Concatenating array
a1 = np.array([23, 4, 76,21, 55])
a2 = np.array([150, 267, 35, 98,256, 750])

## Concatenating the array using concatenate()
a1a2 = np.concatenate([a1, a2])

## Printing the concatenated array
print("The concatenated array \n",a1a2)

The concatenated array 
 [ 23   4  76  21  55 150 267  35  98 256 750]


In [46]:
a1 = np.array([(1,2,3),(3,4,5)])
a2 = a1 * 2
print(a1)
print(a2)
np.concatenate([a1,a2])

a1[1,1] = 100

print(a1)

[[1 2 3]
 [3 4 5]]
[[ 2  4  6]
 [ 6  8 10]]
[[  1   2   3]
 [  3 100   5]]


In [96]:
## Concatenating 2D array

a1 = np.array([['James', 24], ['Smith',21], ['Bob',45]])
a2 = np.array([['Amy',21],['Charles', 28]])

## Concatenating the 2D array using concatenate()
a1a2 = np.concatenate([a1, a2])   
               
## Printing the concatenated 2d Array
print("The concatenated 2D array\n",a1a2)

The concatenated 2D array
 [['James' '24']
 ['Smith' '21']
 ['Bob' '45']
 ['Amy' '21']
 ['Charles' '28']]


In [103]:
## Using flatten() to convert multi dimentional array to a single dimention array
a1 = np.array([[150, 267], [35, 98],[256, 750]])

## Printing the array
print("The 2D array \n", a1)

## The flattened array
print("\nThe flattened array \n", np.ndarray.flatten(a1))

The 2D array 
 [[150 267]
 [ 35  98]
 [256 750]]

The flattened array 
 [150 267  35  98 256 750]


In [107]:
## Books Array
books = np.array([['Python for Data Science','Intro to Machine Learning','Intro to Deep Learning'],[35, 51.5, 43]])

## Printing the dimension of Books array
print("The dimension of 'books' array is : ",books.ndim,'\n\n')

## We can iterate the array using for loop
## Printing each element of the array using for loop
for i in books:
    print(i)
    
## Printing each element separately
print("\n\nPrinting each element in 2D array separately\n")
for i in books:
    for j in i:
        print(j)

The dimension of 'books' array is :  2 


['Python for Data Science' 'Intro to Machine Learning'
 'Intro to Deep Learning']
['35' '51.5' '43']


Printing each element in 2D array separately

Python for Data Science
Intro to Machine Learning
Intro to Deep Learning
35
51.5
43


The Numpy arrays are faster than lists.  We can see through an example.

In [47]:
import time

## Declaring size of an array and lists
size = 1000000

## Creating a lists
l1 = range(size)
l2 = range(size)

starttime = time.time()
resultlist = [(a * b) for a, b in zip(l1, l2)]

## Calculating the time taken for processing lists
print("The time taken for processing lists : ",(time.time() - starttime),'seconds')

The time taken for processing lists :  0.12865495681762695 seconds


In [48]:
## Creating 2 arrays
a1 = np.arange(size)
a2 = np.arange(size)

starttime = time.time()
resultarray = a1 * a2

## Calculating the time taken for processing array
print("The time taken for processing arrays : ",(time.time() - starttime),'seconds')

The time taken for processing arrays :  0.0019960403442382812 seconds
